### PR TITLE
Src integration

### PR DESCRIPTION
**Pull request by lheagy**
Adapted rhs and source terms so it is clear where we are performing integration on the source vectors. For the E-B formulation, we integrate s_e, for the H-J formulation, we integrate s_m. See docs in FDEM.py.

### CODE REVIEW

**Comment by lheagy** [comment]
@sgkang : can you have a look when you have some time??

**Comment by sgkang** [comment]
Hi @lheagy 

That looks good to me on most cases. And now it's more explicit and clear. 
But, I just think about implementation of Christoph's line current code. 
In that case, this functions outputs Me*js, which integrated currents. 
Thus, we do not have to multiply Me again for this case. Probably, we can put an option ... for this.
Think about this, and we can get together next week.

**Comment by lheagy** [comment]
Thanks Seogi! I moved the integration so that it takes place inside of the definition of the source (instead of in the problem). This should make it easier to trigger on / off (I also realized it is also important to be able to turn off for primary-secondary approaches).

**Comment by rowanc1** [comment]
This issue was moved to simpeg/simpeg#158

**Pull request merged**
